services:
  kache:
    image: kacheio/kache:main
    restart: unless-stopped
    command:
      - "-config.file=/kache.yml"
    ports:
      - 127.0.0.1:8000:8000
    links:
      - api
      - redis
    volumes:
      - ./kache.yml:/kache.yml

  api:
    build: .
    command: "--workers 4"
    restart: unless-stopped
    links:
      - redis
    environment:
      REDIS_URL: redis://redis

  redis:
    image: redis
    restart: unless-stopped
